INSERT INTO Classe (Nom_Classe, Niveau) VALUES
('Informatique - Débutant', 'Débutant'),
('Mathématiques - Avancé', 'Avancé'),
('Physique - Intermédiaire', 'Intermédiaire'),
('Biologie - Débutant', 'Débutant'),
('Histoire - Moyen Âge', 'Intermédiaire'),
('Chimie - Organique', 'Avancé'),
('Littérature - XIXe siècle', 'Intermédiaire'),
('Philosophie - Éthique', 'Débutant'),
('Géographie - Urbaine', 'Avancé'),
('Économie - Microéconomie', 'Intermédiaire'),
('Langues Étrangères - Anglais', 'Débutant'),
('Informatique - Intelligence Artificielle', 'Avancé'),
('Mathématiques - Topologie', 'Avancé'),
('Histoire de l’Art', 'Intermédiaire'),
('Sciences Politiques', 'Avancé'),
('Droit International', 'Intermédiaire'),
('Physique - Thermodynamique', 'Avancé'),
('Littérature - Poésie', 'Débutant'),
('Chimie - Physique', 'Intermédiaire'),
('Biologie - Écologie', 'Débutant');
