INSERT INTO Cours (Nom_Cours, Description, Credit) VALUES
('Développement Web', 'Introduction aux technologies du web, HTML, CSS, JavaScript', 5),
('Analyse et Algèbre', 'Étude des fonctions, dérivées, intégrales et matrices', 6),
('Mécanique Quantique', 'Principes de la mécanique quantique, physique des particules', 5),
('Génétique', 'Étude des gènes, héritabilité et mutation', 4),
('Moyen Âge', 'Histoire de l’Europe au Moyen Âge', 3),
('Chimie Organique', 'Réactions chimiques et structures organiques', 5),
('Littérature du XIXe siècle', 'Analyse des grands auteurs du XIXe siècle', 4),
('Éthique et Morale', 'Philosophie sur les concepts du bien et du mal', 3),
('Géographie Urbaine', 'Étude des villes et de leur développement géographique', 3),
('Microéconomie', 'Introduction à l’économie et aux décisions des agents économiques', 5),
('Langues Étrangères', 'Apprentissage des bases de l’anglais', 3),
('Intelligence Artificielle', 'Principes de l’intelligence artificielle et ses applications', 6),
('Topologie', 'Étude des espaces topologiques et de leurs propriétés', 5),
('Histoire de l’Art', 'Histoire des mouvements artistiques et des grandes œuvres', 4),
('Gouvernance Internationale', 'Étude des relations internationales et du droit international', 5),
('Droit International', 'Les règles juridiques régissant les relations entre les États', 6),
('Thermodynamique', 'Les lois de la thermodynamique et leurs applications', 4),
('Poésie Française', 'Analyse de la poésie française à travers les siècles', 3),
('Chimie Physique', 'Étude des principes de la chimie à l’échelle moléculaire', 5),
('Écologie', 'L’étude des interactions entre les organismes et leur environnement', 4);
