INSERT INTO Enseignant (ID_Enseignant, ID_Utilisateur, Departement, Specialite) VALUES
(1, 14, 'Informatique', 'Développement web'),
(2, 11, 'Mathématiques', 'Analyse et Algèbre'),
(3, 18, 'Physique', 'Mécanique quantique'),
(4, 6, 'Biologie', 'Génétique'),
(5, 15, 'Histoire', 'Moyen Âge'),
(6, 2, 'Chimie', 'Chimie organique'),
(7, 13, 'Littérature', 'Littérature française du XIXe siècle'),
(8, 8, 'Philosophie', 'Éthique et morale'),
(9, 12, 'Géographie', 'Géographie urbaine'),
(10, 1, 'Économie', 'Microéconomie'),
(11, 17, 'Langues étrangères', 'Anglais'),
(12, 5, 'Informatique', 'Intelligence artificielle'),
(13, 10, 'Mathématiques', 'Topologie'),
(14, 7, 'Histoire', 'Histoire de l’art'),
(15, 9, 'Sciences politiques', 'Gouvernance internationale'),
(16, 20, 'Droit', 'Droit international'),
(17, 16, 'Physique', 'Thermodynamique'),
(18, 3, 'Littérature', 'Poésie française'),
(19, 19, 'Chimie', 'Chimie physique'),
(20, 4, 'Biologie', 'Écologie');
